### ISSUE TITLE
Implementation of QG-Adam optimizer

### ISSUE THREAD

**Issue by aparna-aketi** [epfml/quasi-global-momentum#1]
Hi @IamTao,
There is an error in the implementation of adam optimizer with qgm at [line 91](https://github.com/epfml/quasi-global-momentum/blob/master/code/pcode/optim/decentralized_qg_adam.py) in decentralized_qg_adam.py. It should be exp_avg.mul_(self.beta1).add_(flatten_grads.buffer, alpha=1-self.beta1) instead of exp_avg.mul_(self.beta1).add_(flatten_grads.buffer, alpha=1). When we tried with this change, qg-adam performs worse than plain adam optimizer and the proposed approximation of adam with quasi momentum does not work. Can you please clarify if alpha=1 is a bug or is intentionally set to 1 (if so what was the intuition)?

**Comment by tlin-taolin** [comment]
Hi, thank you for your interest!

Indeed it is not a mistake: we explored different variants of QG-Adam and found that this one performs better (and used it in our experiments). We also provided another [variant](https://github.com/epfml/quasi-global-momentum/blob/master/code/pcode/optim/decentralized_qg_adam_v1.py) for your reference.

But please note that these QG-Adam variants have no theoretical guarantee yet, with much less performance gain than our QG-SGDm (which is the main focus of the paper). We believe improving these Adam variants (or more precisely, how to use the normalized update for Adam-like update scheme) is a very interesting future direction.

**Comment by aparna-aketi** [comment]
Thanks for the clarification!
